name: kodi 插件自动化
on:
  push:
    branches:
    - py3

jobs: 
  my-job: 
    runs-on: ubuntu-latest
    name: 打包Kodi插件并自动更新插件库
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 运行python
      run: |
        python3 .github/auto.py
    - name: Commit 文件
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add repo
        git add addons.xml
        git add addons.xml.md5
        git commit -m "[bot] 自动打包插件并推送到存储库"
    - name: Push 到 Github
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: py3
        repository: ArchieMeng/xbmc-kodi-private-china-addons
        directory: .